import type { OpenSourceManifest, OpenSourcePackage } from '~/types/about';

/** Where the npm manifest is served from (generated by scripts/gen-licenses.mjs). */
const NPM_MANIFEST_URL = '/open-source.json';

/**
 * Case-insensitive substring filter on the package NAME (story 101: "filterable
 * by library name"). Version and license are deliberately not searched, so the
 * <mark> highlight in the UI always corresponds to what matched.
 *
 * Exported separately from the composable so it can be unit-tested and reused by
 * the list component without a Nuxt runtime.
 */
export function filterOpenSourcePackages(
  packages: OpenSourcePackage[],
  term: string,
): OpenSourcePackage[] {
  const needle = term.trim().toLowerCase();
  if (!needle) return packages;
  return packages.filter((pkg) => pkg.name.toLowerCase().includes(needle));
}

/**
 * Type guard for a manifest received over the wire. Needed because a missing
 * `public/open-source.json` does NOT 404 in an SPA — the dev server / static
 * host answers with the index.html fallback, which would otherwise flow through
 * as a "successful" response and blow up in the template.
 */
function isManifest(value: unknown): value is OpenSourceManifest {
  return (
    !!value &&
    typeof value === 'object' &&
    Array.isArray((value as OpenSourceManifest).packages)
  );
}

/**
 * Loads both halves of the attribution list. The two sources are independent:
 * a failing API call must not hide the npm list (and vice versa), so each has
 * its own error string.
 */
export function useOpenSourceAttribution() {
  const backendPackages = ref<OpenSourcePackage[]>([]);
  const frontendPackages = ref<OpenSourcePackage[]>([]);
  const backendNote = ref('');
  const frontendNote = ref('');
  const backendError = ref<string | null>(null);
  const frontendError = ref<string | null>(null);
  const loading = ref(false);

  async function loadBackend() {
    const api = useApi();
    try {
      // Wrapped in the { status, data } envelope, which useApi unwraps.
      const manifest = await api<OpenSourceManifest>('/api/v1/about/open-source');
      if (!isManifest(manifest)) throw new Error('malformed manifest');
      backendPackages.value = manifest.packages;
      backendNote.value = manifest.note ?? '';
      backendError.value = null;
    } catch {
      backendPackages.value = [];
      backendError.value = 'Could not load the backend dependency list.';
    }
  }

  async function loadFrontend() {
    try {
      // Native fetch, NOT useApi/$fetch: the manifest is a static asset of this
      // SPA served from its own origin, not an API endpoint (useApi would prefix
      // the configured API base URL and attach a bearer token). Nuxt's $fetch is
      // injected at transform time, which makes it unstubbable in specs (see the
      // note in composables/useApi.spec.ts); plain fetch keeps this hermetic.
      const response = await fetch(NPM_MANIFEST_URL);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const manifest: unknown = await response.json();
      if (!isManifest(manifest)) throw new Error('malformed manifest');
      frontendPackages.value = manifest.packages;
      frontendNote.value = manifest.note ?? '';
      frontendError.value = null;
    } catch {
      frontendPackages.value = [];
      frontendError.value = 'Could not load the frontend dependency list.';
    }
  }

  async function load() {
    loading.value = true;
    try {
      await Promise.all([loadBackend(), loadFrontend()]);
    } finally {
      loading.value = false;
    }
  }

  return {
    backendPackages,
    frontendPackages,
    backendNote,
    frontendNote,
    backendError,
    frontendError,
    loading,
    load,
  };
}
